package alphabet

func MakeCodonDict() map[string]string {

	codonAA := make(map[string]string)

	codonAA["TTT"] = "F"
	codonAA["TTC"] = "F"
	codonAA["TTA"] = "L"
	codonAA["TTG"] = "L"
	codonAA["TCT"] = "S"
	codonAA["TCC"] = "S"
	codonAA["TCA"] = "S"
	codonAA["TCG"] = "S"
	codonAA["TAT"] = "Y"
	codonAA["TAC"] = "Y"
	codonAA["TAA"] = "*"
	codonAA["TAG"] = "*"
	codonAA["TGT"] = "C"
	codonAA["TGC"] = "C"
	codonAA["TGA"] = "*"
	codonAA["TGG"] = "W"

	codonAA["CTT"] = "L"
	codonAA["CTC"] = "L"
	codonAA["CTA"] = "L"
	codonAA["CTG"] = "L"
	codonAA["CCT"] = "P"
	codonAA["CCC"] = "P"
	codonAA["CCA"] = "P"
	codonAA["CCG"] = "P"
	codonAA["CAT"] = "H"
	codonAA["CAC"] = "H"
	codonAA["CAA"] = "Q"
	codonAA["CAG"] = "Q"
	codonAA["CGT"] = "R"
	codonAA["CGC"] = "R"
	codonAA["CGA"] = "R"
	codonAA["CGG"] = "R"

	codonAA["ATT"] = "I"
	codonAA["ATC"] = "I"
	codonAA["ATA"] = "I"
	codonAA["ATG"] = "M"
	codonAA["ACT"] = "T"
	codonAA["ACC"] = "T"
	codonAA["ACA"] = "T"
	codonAA["ACG"] = "T"
	codonAA["AAT"] = "N"
	codonAA["AAC"] = "N"
	codonAA["AAA"] = "K"
	codonAA["AAG"] = "K"
	codonAA["AGT"] = "S"
	codonAA["AGC"] = "S"
	codonAA["AGA"] = "R"
	codonAA["AGG"] = "R"

	codonAA["GTT"] = "V"
	codonAA["GTC"] = "V"
	codonAA["GTA"] = "V"
	codonAA["GTG"] = "V"
	codonAA["GCT"] = "A"
	codonAA["GCC"] = "A"
	codonAA["GCA"] = "A"
	codonAA["GCG"] = "A"
	codonAA["GAT"] = "D"
	codonAA["GAC"] = "D"
	codonAA["GAA"] = "E"
	codonAA["GAG"] = "E"
	codonAA["GGT"] = "G"
	codonAA["GGC"] = "G"
	codonAA["GGA"] = "G"
	codonAA["GGG"] = "G"

	return codonAA
}
